application:
  title: Learning project

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
